name: Build and publish - Pre Release

on:
  pull_request:
    branches:
      - main

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Add .npmrc file
        run: |
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_AUTH_TOKEN }}" >> .npmrc
          chmod 0600 .npmrc

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

      - name: Build project
        run: pnpm run build

      - name: Auth Git
        run: |
          git config --global user.name KatKmiotek
          git config --global user.email katarzyna.kmiotek@yahoo.com

      - name: Bump version - pre release
        run: pnpm version prerelease --preid=alpha

      - name: Publish package
        run: pnpm publish --no-git-checks --registry https://npm.pkg.github.com/KatKmiotek
